### ISSUE TITLE
Issue on city_distance.py

### ISSUE THREAD

**Issue by ghost** [PyOCL/pyopencl-examples#1]
I use anaconda3 and pyopencl there and running example I got error

```
(cl) ~/work/p1/pyopencl-examples/1-3$ python city_distance.py 
load program from cl source file
prepare data
create context
Choose platform:
[0] <pyopencl.Platform 'Intel(R) OpenCL HD Graphics' at 0x1f8c6c0>
[1] <pyopencl.Platform 'Experimental OpenCL 2.1 CPU Only Platform' at 0x1f6ddc0>
Choice [0]:0
Set the environment variable PYOPENCL_CTX='0' to avoid being asked again.
create command queue
prepare device memory for input / output
compile kernel code
execute kernel programs
wait for kernel executions
elapsed time: 0.094729371
Traceback (most recent call last):
  File "city_distance.py", line 49, in <module>
    cl.enqueue_read_buffer(queue, dev_fianl, final).wait()
AttributeError: module 'pyopencl' has no attribute 'enqueue_read_buffer'
(cl) ~/work/p1/pyopencl-examples/1-3$ 

```

as well for 2-1-implicit
```

(cl) ~/work/p1/pyopencl-examples/2-1-implicit$ python adjust_score.py 
load program from cl source file
prepare data ... 
create context
Choose platform:
[0] <pyopencl.Platform 'Intel(R) OpenCL HD Graphics' at 0x179dd70>
[1] <pyopencl.Platform 'Experimental OpenCL 2.1 CPU Only Platform' at 0x12b0220>
Choice [0]:0
Set the environment variable PYOPENCL_CTX='0' to avoid being asked again.
create command queue
prepare device memory for input / output
compile kernel code
execute kernel programs
wait for kernel executions
Traceback (most recent call last):
  File "adjust_score.py", line 45, in <module>
    cl.enqueue_read_buffer(queue, dev_fianl, final).wait()
AttributeError: module 'pyopencl' has no attribute 'enqueue_read_buffer'
(cl) ~/work/p1/pyopencl-examples/2-1-implicit$ 

```

**Comment by kilikkuo** [comment]
@peter73421 , may I know the detailed software version for your environment.  It sounds like a version issue for me, AFAIK, `enqueue_read_buffer` should still can be found in pyopencl github repo [1].
So I'd like to know what OS you used and anaconda, pyopencl version number, thanks. 


[1] https://github.com/inducer/pyopencl

**Comment by john-hu** [comment]
@peter73421

I found the latest version had removed the enqueue_read_buffer. That doesn't make sense.

**Comment by john-hu** [comment]
@peter73421 I got it. The enqueue_read_buffer is deprecated since 2011. But it seems nobody knows it, see this [comment](https://github.com/inducer/pyopencl/issues/256#issuecomment-437069080). We will modify our code to use another method.

BTW, @peter73421 , you can modify the code to keep it running with `_enqueue_read_buffer`. It's still there. Sorry about that. We will fix it.

**Comment by john-hu** [comment]
@kilikkuo  We should modify the code to use `enqueue_copy` instead of `enqueue_whatever_whoever`

**Comment by ghost** [comment]
I use anaconda3

```
(cl) ~/work/p1/pyopencl-examples$ python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyopencl as cl
>>> cl.VERSION
(2018, 2, 1)
>>> 
```

**Comment by ghost** [comment]
Under other machine I use with python2
```
root:~/pyopencl-examples/1-2# python adjust_score.py 
load program from cl source file
Traceback (most recent call last):
  File "adjust_score.py", line 11, in <module>
    f = open('adjust_score.cl', 'r', encoding='utf-8')
TypeError: 'encoding' is an invalid keyword argument for this function

```

with python2
```
root:~/pyopencl-examples/1-2# python
Python 2.7.12 (default, Aug 28 2018, 17:44:47) 
[GCC 6.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 

```

**Comment by john-hu** [comment]
Python2 should also work. But we use python3 syntax. You may need to remove or modify the python3 syntax. We would suggest using python3.

The output is correct at your Anaconda. You can modify the code to replace `enqueue_read_buffer` to `_enqueue_read_buffer` to workaround it temporarily.
